"""Add starter_code field to problems table

Revision ID: 8b3473ee6022
Revises: 5b3f1e9c2b7c
Create Date: 2025-11-21 14:40:41.364698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3473ee6022'
down_revision: Union[str, None] = '5b3f1e9c2b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('starter_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'starter_code')
    # ### end Alembic commands ###
